### ISSUE TITLE
Cannot offer PREVIEW features to the customer, please make a filter

### ISSUE THREAD

**Issue by henriquebrisola** [kvaes/azure-vmchooser-docs#2]
The main issue of a PREVIEW feature is that you have no support if it fails and it's not recommended to use on production environments. As I work assessing company's on-premises datacenters aiming to Azure, everything is "critical", or, at least, too important to make use of something that is not reliable.
Please create a column that filter those services that are still in preview stage.
E.g., if I use bulk uploader and have some VMs with high amount of disk capacity, VmChooser will offer me to Raid0 some Data Disks, but sometimes it offers me p60, p70 and p80 disks, which are in preview.

**Comment by kvaes** [comment]
Same initial message as ; https://github.com/kvaes/azure-vmchooser-docs/issues/1 

I understand your point of view. The issue here for me is that in the automated import of the data, it's very tedious to filter out the preview information.Though I've added it as a feature request ; https://github.com/kvaes/azure-vmchooser-frontend-v3/issues/12
